name: Windows CMake Build

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Setup CMake
      uses: lukka/run-cmake@v10
      with:
        cmakeVersion: '3.28.0'  # Version fixe recommandée

    - name: Créer le répertoire de build
      run: mkdir -p build

    - name: Configurer CMake
      working-directory: build
      shell: cmd
      run: cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release

    - name: Compiler le projet
      working-directory: build
      shell: cmd
      run: cmake --build . --config Release --parallel 4

    - name: Exécuter les tests
      working-directory: build
      shell: cmd
      run: ctest -C Release --output-on-failure
