name: Windows CMake Build

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  build:
    runs-on: windows-latest  # Environnement Windows Server 2022

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Configurer CMake
      uses: ms-actions/cmake-helper@v1
      with:
        cmake-version: '3.28'  # Version spécifique ou 'latest'

    - name: Créer le répertoire de build
      run: mkdir build

    - name: Configurer le projet
      working-directory: ./build
      run: cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release

    - name: Compiler le projet
      working-directory: ./build
      run: cmake --build . --config Release --target ALL_BUILD

    - name: Exécuter les tests (optionnel)
      working-directory: ./build
      run: ctest -C Release
